---
name: Documentation

"on":
  push:
    paths:
      - 'docs/**'
    branches:
      - 'main'

env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
  REQUIREMENTS: docs-requirements.txt

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry export --without-hashes --only docs > ${REQUIREMENTS}
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTRA_PACKAGES: build-base
